# An example of ClusterConfig object with custom VPC IPv4 CIDR,
# and auto-allocated IPv6 CIDRs for all subnets; also without
# any nodegroups:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-demo
  region: eu-central-1

vpc:
  cidr: 10.30.0.0/16
  autoAllocateIPv6: false
  # disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: true
    privateAccess: false

nodeGroups:
  - name: ng1-public
    instanceType: m5.large
    instanceName: custom-node-name
    desiredCapacity: 1
  
